name = "<%= name %>"
type = "javascript"
zone_id = "<%= zone_id %>"
account_id = "<%= account_id %>"
route = "<%= route_id %>"
workers_dev = true

[build]
command = "nx run <%= name %>:build"
[build.upload]
format = "service-worker"
